
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        log
* GENERATION DATE:  29.05.2014
* CLASS FILE:       C:\xampp\htdocs\inexato/class/log.php
* FOR MYSQL TABLE:  log
* FOR MYSQL DB:     inexato
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class/database.php");

// **********************
// CLASS DECLARATION
// **********************

class log
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $cd_log;   // KEY ATTR. WITH AUTOINCREMENT

var $cd_usuario;   // (normal Attribute)
var $nm_acao;   // (normal Attribute)
var $dt_log;   // (normal Attribute)
var $ds_log;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function log()
{

	$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getcd_log()
{
	return $this->cd_log;
}

function getcd_usuario()
{
	return $this->cd_usuario;
}

function getnm_acao()
{
	return $this->nm_acao;
}

function getdt_log()
{
	return $this->dt_log;
}

function getds_log()
{
	return $this->ds_log;
}

// **********************
// SETTER METHODS
// **********************


function setcd_log($val)
{
	$this->cd_log =  $val;
}

function setcd_usuario($val)
{
	$this->cd_usuario =  $val;
}

function setnm_acao($val)
{
	$this->nm_acao =  $val;
}

function setdt_log($val)
{
	$this->dt_log =  $val;
}

function setds_log($val)
{
	$this->ds_log =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

	$sql =  "SELECT * FROM log WHERE cd_log = $id;";
	$result =  $this->database->query($sql);
	$result = $this->database->result;
	$row = mysql_fetch_object($result);

	
	$this->cd_log = $row->cd_log;
	
	$this->cd_usuario = $row->cd_usuario;
	
	$this->nm_acao = $row->nm_acao;
	
	$this->dt_log = $row->dt_log;
	
	$this->ds_log = $row->ds_log;
	
}

// **********************
// DELETE
// **********************

function delete($id)
{
	$sql = "DELETE FROM log WHERE cd_log = $id;";
	$result = $this->database->query($sql);
	
}

// **********************
// INSERT
// **********************

function insert()
{
	$this->cd_log = ""; // clear key for autoincrement

	$sql = "INSERT INTO log ( cd_usuario,nm_acao,dt_log,ds_log ) VALUES ( '$this->cd_usuario','$this->nm_acao','$this->dt_log','$this->ds_log' )";
	$result = $this->database->query($sql);
	$this->cd_log = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



	$sql = " UPDATE log SET  cd_usuario = '$this->cd_usuario',nm_acao = '$this->nm_acao',dt_log = '$this->dt_log',ds_log = '$this->ds_log' WHERE cd_log = $id ";

	$result = $this->database->query($sql);


	
}


} // class : end

?>
<!-- end of generated class -->
