<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        usuario
* GENERATION DATE:  28.05.2014
* CLASS FILE:       C:\xampp\htdocs\inexato/class/usuario.php
* FOR MYSQL TABLE:  usuario
* FOR MYSQL DB:     inexato
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("class/database.php");
include_once("class/criptografia.php");
include_once("class/log.php");

// **********************
// CLASS DECLARATION
// **********************

class usuario
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $cd_usuario;   // KEY ATTR. WITH AUTOINCREMENT

var $cd_tipo;   // (normal Attribute)
var $nm_usuario;   // (normal Attribute)
var $snm_usuario;   // (normal Attribute)
var $cd_cpf;   // (normal Attribute)
var $tx_email;   // (normal Attribute)
var $tx_senha;   // (normal Attribute)
var $nm_endereco;   // (normal Attribute)
var $cd_numero;   // (normal Attribute)
var $ds_complemento_numero;   // (normal Attribute)
var $nm_bairro;   // (normal Attribute)
var $nm_cidade;   // (normal Attribute)
var $nm_estado;   // (normal Attribute)
var $cd_cep;   // (normal Attribute)
var $nm_pais;   // (normal Attribute)
var $cd_telefone;   // (normal Attribute)
var $cd_celular;   // (normal Attribute)
var $dt_criacao;   // (normal Attribute)
var $cd_ativo;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function usuario()
{

	$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getcd_usuario()
{
	return $this->cd_usuario;
}

function getcd_tipo()
{
	return $this->cd_tipo;
}

function getnm_usuario()
{
	return $this->nm_usuario;
}

function getsnm_usuario()
{
	return $this->snm_usuario;
}

function getcd_cpf()
{
	return $this->cd_cpf;
}

function gettx_email()
{
	return $this->tx_email;
}

function gettx_senha()
{
	return $this->tx_senha;
}

function getnm_endereco()
{
	return $this->nm_endereco;
}

function getcd_numero()
{
	return $this->cd_numero;
}

function getds_complemento_numero()
{
	return $this->ds_complemento_numero;
}

function getnm_bairro()
{
	return $this->nm_bairro;
}

function getnm_cidade()
{
	return $this->nm_cidade;
}

function getnm_estado()
{
	return $this->nm_estado;
}

function getcd_cep()
{
	return $this->cd_cep;
}

function getnm_pais()
{
	return $this->nm_pais;
}

function getcd_telefone()
{
	return $this->cd_telefone;
}

function getcd_celular()
{
	return $this->cd_celular;
}

function getdt_criacao()
{
	return $this->dt_criacao;
}

function getcd_ativo()
{
	return $this->cd_ativo;
}

// **********************
// SETTER METHODS
// **********************


function setcd_usuario($val)
{
	$this->cd_usuario =  $val;
}

function setcd_tipo($val)
{
	$this->cd_tipo =  $val;
}

function setnm_usuario($val)
{
	$this->nm_usuario =  $val;
}

function setsnm_usuario($val)
{
	$this->snm_usuario =  $val;
}

function setcd_cpf($val)
{
	$this->cd_cpf =  $val;
}

function settx_email($val)
{
	$this->tx_email =  $val;
}

function settx_senha($val)
{
	$this->tx_senha =  $val;
}

function setnm_endereco($val)
{
	$this->nm_endereco =  $val;
}

function setcd_numero($val)
{
	$this->cd_numero =  $val;
}

function setds_complemento_numero($val)
{
	$this->ds_complemento_numero =  $val;
}

function setnm_bairro($val)
{
	$this->nm_bairro =  $val;
}

function setnm_cidade($val)
{
	$this->nm_cidade =  $val;
}

function setnm_estado($val)
{
	$this->nm_estado =  $val;
}

function setcd_cep($val)
{
	$this->cd_cep =  $val;
}

function setnm_pais($val)
{
	$this->nm_pais =  $val;
}

function setcd_telefone($val)
{
	$this->cd_telefone =  $val;
}

function setcd_celular($val)
{
	$this->cd_celular =  $val;
}

function setdt_criacao($val)
{
	$this->dt_criacao =  $val;
}

function setcd_ativo($val)
{
	$this->cd_ativo =  $val;
}

// **********************
// LOGIN LOGIN / LOGOUT
// **********************

function login($tx_email, $password)
{

	$sql =  "SELECT * FROM usuario WHERE tx_email = '$tx_email';";
	$result =  $this->database->query($sql);
	$result = $this->database->result;
	$row = mysql_fetch_object($result);

	if (Bcrypt::check($password, $row->tx_senha)) {

		$this->cd_usuario = $row->cd_usuario;
		$this->cd_tipo = $row->cd_tipo;
		$this->nm_usuario = $row->nm_usuario;
		$this->snm_usuario = $row->snm_usuario;
		$this->cd_cpf = $row->cd_cpf;
		$this->tx_email = $row->tx_email;
		$this->tx_senha = $row->tx_senha;
		$this->nm_endereco = $row->nm_endereco;
		$this->cd_numero = $row->cd_numero;
		$this->ds_complemento_numero = $row->ds_complemento_numero;
		$this->nm_bairro = $row->nm_bairro;
		$this->nm_cidade = $row->nm_cidade;
		$this->nm_estado = $row->nm_estado;
		$this->cd_cep = $row->cd_cep;
		$this->nm_pais = $row->nm_pais;
		$this->cd_telefone = $row->cd_telefone;
		$this->cd_celular = $row->cd_celular;
		$this->dt_criacao = $row->dt_criacao;
		$this->cd_ativo = $row->cd_ativo;
		$_SESSION['usuario']['cd_usuario'] = $row->cd_usuario;
		$log = new log();
		$log->gravar($row->cd_usuario,"login");

		return true;

	} else {

		session_destroy();
		return false;

	}

}

function logout()
{
		session_destroy();
}


// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM usuario WHERE cd_usuario = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->cd_usuario = $row->cd_usuario;

$this->cd_tipo = $row->cd_tipo;

$this->nm_usuario = $row->nm_usuario;

$this->snm_usuario = $row->snm_usuario;

$this->cd_cpf = $row->cd_cpf;

$this->tx_email = $row->tx_email;

$this->tx_senha = $row->tx_senha;

$this->nm_endereco = $row->nm_endereco;

$this->cd_numero = $row->cd_numero;

$this->ds_complemento_numero = $row->ds_complemento_numero;

$this->nm_bairro = $row->nm_bairro;

$this->nm_cidade = $row->nm_cidade;

$this->nm_estado = $row->nm_estado;

$this->cd_cep = $row->cd_cep;

$this->nm_pais = $row->nm_pais;

$this->cd_telefone = $row->cd_telefone;

$this->cd_celular = $row->cd_celular;

$this->dt_criacao = $row->dt_criacao;

$this->cd_ativo = $row->cd_ativo;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM usuario WHERE cd_usuario = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->cd_usuario = ""; // clear key for autoincrement

$sql = "INSERT INTO usuario ( cd_tipo,nm_usuario,snm_usuario,cd_cpf,tx_email,tx_senha,nm_endereco,cd_numero,ds_complemento_numero,nm_bairro,nm_cidade,nm_estado,cd_cep,nm_pais,cd_telefone,cd_celular,dt_criacao,cd_ativo ) VALUES ( '$this->cd_tipo','$this->nm_usuario','$this->snm_usuario','$this->cd_cpf','$this->tx_email','Bcrypt::hash($this->tx_senha)','$this->nm_endereco','$this->cd_numero','$this->ds_complemento_numero','$this->nm_bairro','$this->nm_cidade','$this->nm_estado','$this->cd_cep','$this->nm_pais','$this->cd_telefone','$this->cd_celular','$this->dt_criacao','$this->cd_ativo' )";
$result = $this->database->query($sql);
$this->cd_usuario = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE usuario SET  cd_tipo = '$this->cd_tipo',nm_usuario = '$this->nm_usuario',snm_usuario = '$this->snm_usuario',cd_cpf = '$this->cd_cpf',tx_email = '$this->tx_email',tx_senha = '$this->tx_senha',nm_endereco = '$this->nm_endereco',cd_numero = '$this->cd_numero',ds_complemento_numero = '$this->ds_complemento_numero',nm_bairro = '$this->nm_bairro',nm_cidade = '$this->nm_cidade',nm_estado = '$this->nm_estado',cd_cep = '$this->cd_cep',nm_pais = '$this->nm_pais',cd_telefone = '$this->cd_telefone',cd_celular = '$this->cd_celular',dt_criacao = '$this->dt_criacao',cd_ativo = '$this->cd_ativo' WHERE cd_usuario = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
